import type { Metadata } from 'next';

import { geistMono, geistSans } from '@/lib/fonts';
import { cn } from '@/lib/utils';

import './globals.css';

export const metadata: Metadata = {
  title: 'Phan Điện ❤️ Vũ Anh',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('antialiased', geistSans.variable, geistMono.variable)}
      >
        {children}
      </body>
    </html>
  );
}
