import type { Metadata } from 'next';

import { StoreProvider } from '@/components/providers';
import { greatVibes, jost, sail } from '@/lib/fonts';
import { cn } from '@/lib/utils';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Phan Điện ❤️ Vũ Anh',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'antialiased',
          jost.variable,
          greatVibes.variable,
          sail.variable,
        )}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
